added possibility to compile module against other kernel than current

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -132,15 +132,18 @@ show_help(){
   echo "                        "
   echo " --module=<opt>         [yes] no: don't compile dvbloopback kernel module"
   echo "                        "
+  echo " --kernel_ver=<opt>     compile kernel for specific kernel version"
+  echo "                        by default current kernel (uname -r)"
   exit 0
 }
 
 ffdecsa_opt="yes"
 compiletype_opt="release"
 v4l_opt="no"
-update_opt="yes"
+update_opt="no" #temporarily disabled update
 binary_opt="yes"
 module_opt="yes"
+kernel_opt=`uname -r`
 
 for opt do
   optval="${opt#*=}"
@@ -169,6 +172,8 @@ for opt do
   ;;
   --help) show_help
   ;;
+  --kernel_ver=*) kernel_opt="$optval"
+  ;;
   *)
   die_unknown $opt
   ;;
@@ -177,10 +182,10 @@ done
 
 # Get kernel version numbers
 
-SHORT_KERNEL=$( echo `uname -r` | grep -o '[[:digit:]]\+\.[[:digit:]]\+' )
-FIRST_DIGIT=$( echo `uname -r` | grep -o '[[:digit:]]\+' | head -n1 )
-SECOND_DIGIT=$( echo `uname -r` | grep -o '[[:digit:]]\+' | awk 'NR==2' )
-DEBIANABIVERS=$( echo `uname -r` | grep -o '[[:digit:]]\+' | awk 'NR==4' )
+SHORT_KERNEL=$( echo ${kernel_opt} | grep -o '[[:digit:]]\+\.[[:digit:]]\+' )
+FIRST_DIGIT=$( echo ${kernel_opt} | grep -o '[[:digit:]]\+' | head -n1 )
+SECOND_DIGIT=$( echo ${kernel_opt} | grep -o '[[:digit:]]\+' | awk 'NR==2' )
+DEBIANABIVERS=$( echo ${kernel_opt} | grep -o '[[:digit:]]\+' | awk 'NR==4' )
 
 # Abort if running kernel is < 3.x
 
@@ -313,7 +318,7 @@ fi
 if ! [ -f "/etc/arch-release" ] > /dev/null  2>&1; then
   # Detect previous installed dvbloopback module
   if [ "x$module_opt" = "xyes" ]; then
-    MODULE=$(find /lib/modules/`uname -r`/ -type f -name "dvbloopback.ko")
+    MODULE=$(find /lib/modules/${kernel_opt}/ -type f -name "dvbloopback.ko")
     if ! [ "$MODULE" = "" ]; then
       echo "
 Existing $MODULE detected.
@@ -325,8 +330,8 @@ Do you want to recompile it?
       if [ "$?" -eq 1 ]; then
         module_opt="no"
       else
-        if ! [ -d /lib/modules/`uname -r`/updates/ffdecsawrapper ]; then
-          mkdir -p /lib/modules/`uname -r`/updates/ffdecsawrapper
+        if ! [ -d /lib/modules/${kernel_opt}/updates/ffdecsawrapper ]; then
+          mkdir -p /lib/modules/${kernel_opt}/updates/ffdecsawrapper
         fi
       fi
     fi
@@ -399,7 +404,7 @@ if [ "x$dvb_path" != "x" ]; then
     experimental_api
   fi
 else
-  if cat /boot/config-`uname -r` | grep "CONFIG_MEDIA_CONTROLLER_DVB=y" > /dev/null 2>&1 ;then
+  if cat /boot/config-${kernel_opt} | grep "CONFIG_MEDIA_CONTROLLER_DVB=y" > /dev/null 2>&1 ;then
     experimental_api
   fi
 fi
@@ -523,12 +528,12 @@ Missing dependency build-essential, marking for installation.
 
   if [ "x$module_opt" = "xyes" ]; then
     if uname -a | egrep 'Debian|Ubuntu' > /dev/null  2>&1; then
-      if ! dpkg-query -l linux-headers-`uname -r` | grep "ii" > /dev/null 2>&1; then
+      if ! dpkg-query -l linux-headers-${kernel_opt} | grep "ii" > /dev/null 2>&1; then
         echo "
-Missing dependency linux-headers-`uname -r`, marking for installation.
+Missing dependency linux-headers-${kernel_opt}, marking for installation.
 
 "
-        apt-get install linux-headers-`uname -r` -y  || die "Error installing dependency linux-headers-`uname -r`"
+        apt-get install linux-headers-${kernel_opt} -y  || die "Error installing dependency linux-headers-${kernel_opt}"
       fi
     fi
 
@@ -579,8 +584,8 @@ fi
 # End Debian Section
 #
 
-FIRST_DIGIT=$(echo `uname -r` | awk -F/ '{print $NF}' | grep -o '[[:digit:]]\+' | head -n1 | awk 'NR==1')
-SECOND_DIGIT=$(echo `uname -r` | awk -F/ '{print $NF}' | grep -o '[[:digit:]]\+' | head -n2 | awk 'NR==2')
+FIRST_DIGIT=$(echo ${kernel_opt} | awk -F/ '{print $NF}' | grep -o '[[:digit:]]\+' | head -n1 | awk 'NR==1')
+SECOND_DIGIT=$(echo ${kernel_opt} | awk -F/ '{print $NF}' | grep -o '[[:digit:]]\+' | head -n2 | awk 'NR==2')
 EXTRA_DIGIT="0"
 VERSION="$FIRST_DIGIT$SECOND_DIGIT"
 chars=`echo -n $SECOND_DIGIT  | wc -c`
@@ -618,8 +623,8 @@ Aborting...
       exit 0
     fi
   else
-    if uname -r | grep "rc" > /dev/null 2>&1; then
-      RC=$(uname -r | cut -d'-' -f2)
+    if echo ${kernel_opt} | grep "rc" > /dev/null 2>&1; then
+      RC=$(${kernel_opt} | cut -d'-' -f2)
       wget https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/plain/include/media/dvbdev.h?id=refs/tags/v$SHORT_KERNEL-$RC -Odvbloopback/module/dvbdev.h
     elif [ "$VERSION" -gt 415 ]; then
       wget https://git.kernel.org/cgit/linux/kernel/git/stable/linux-stable.git/plain/include/media/dvbdev.h?id=refs/tags/v$SHORT_KERNEL -Odvbloopback/module/dvbdev.h
@@ -634,13 +639,13 @@ fi
 
 if [ "x$module_opt" = "xyes" ]; then
   if [ "x$dvb_path" = "x" ]; then
-    if [ -f /lib/modules/`uname -r`/build/Module.symvers ]; then
-      cp -f /lib/modules/`uname -r`/build/Module.symvers dvbloopback/module/Module.symvers
+    if [ -f /lib/modules/${kernel_opt}/build/Module.symvers ]; then
+      cp -f /lib/modules/${kernel_opt}/build/Module.symvers dvbloopback/module/Module.symvers
     else echo -en "
 \E[1;33;44m
 ERROR!!!
 
-could not locate /lib/modules/`uname -r`/build/Module.symvers
+could not locate /lib/modules/${kernel_opt}/build/Module.symvers
 
 Aborting...
 \E[0m
@@ -734,7 +739,7 @@ Bad option to --compiletype '$compiletype_opt' Should be 'release, debug'
 fi
 
 echo "
-`uname -r` kernel detected.
+${kernel_opt} kernel detected.
 Using C++ compiler: $CXX"
 
 if [ "x$compiletype_opt" = "xrelease" ]; then
@@ -755,6 +760,9 @@ fi
 
 echo "CXX=$CXX" >> config.mak
 echo "CC=$CC" >> config.mak
+
+# Configure build directory
+echo "BUILD_DIR=/lib/modules/${kernel_opt}/build" >> config.mak
 
 # Compile and, if running Debian/Ubuntu or CentOS 7,
 # finish by installing the lot.
@@ -813,7 +821,7 @@ Do you want to install ffdecsawrapper binary and/or dvbloopback kernel module?
 
 Binary's location: /usr/bin/ffdecsawrapper
 
-dvbloopback module: /usr/lib/modules/`uname -r`/updates/ffdecsawrapper/dvbloopback.ko
+dvbloopback module: /usr/lib/modules/${kernel_opt}/updates/ffdecsawrapper/dvbloopback.ko
 
 "
       confirmyes "Yes, install now! [Y/n]"
@@ -828,11 +836,11 @@ dvbloopback module: /usr/lib/modules/`uname -r`/updates/ffdecsawrapper/dvbloopba
         fi
       fi
       if [ "x$module_opt" = "xyes" ]; then
-        if [ -e /usr/lib/modules/`uname -r`/updates/ffdecsawrapper/dvbloopback.ko ]; then
-          rm -f /usr/lib/modules/`uname -r`/updates/ffdecsawrapper/dvbloopback.ko
+        if [ -e /usr/lib/modules/${kernel_opt}/updates/ffdecsawrapper/dvbloopback.ko ]; then
+          rm -f /usr/lib/modules/${kernel_opt}/updates/ffdecsawrapper/dvbloopback.ko
         fi
-        /usr/bin/install dvbloopback.ko /usr/lib/modules/`uname -r`/updates/ffdecsawrapper
-        depmod -a
+        /usr/bin/install dvbloopback.ko /usr/lib/modules/${kernel_opt}/updates/ffdecsawrapper
+        depmod -a -b /lib/modules/${kernel-opt}
       fi
     fi
   fi
@@ -948,7 +956,7 @@ Do you want to install ffdecsawrapper binary and/or dvbloopback kernel module?
 
 Binary's location: /usr/bin/ffdecsawrapper
 
-dvbloopback module: /lib/modules/`uname -r`/updates/ffdecsawrapper/dvbloopback.ko
+dvbloopback module: /lib/modules/${kernel_opt}/updates/ffdecsawrapper/dvbloopback.ko
 
 If you hit Y and your kernel needs to be patched, that will be done too.
 
@@ -964,12 +972,12 @@ If you hit Y and your kernel needs to be patched, that will be done too.
         cp -f ffdecsawrapper /usr/bin
       fi
       if [ "x$module_opt" = "xyes" ]; then
-        if [ -e /lib/modules/`uname -r`/updates/ffdecsawrapper/dvbloopback.ko ]; then
-          rm -f /lib/modules/`uname -r`/updates/ffdecsawrapper/dvbloopback.ko
+        if [ -e /lib/modules/${kernel_opt}/updates/ffdecsawrapper/dvbloopback.ko ]; then
+          rm -f /lib/modules/${kernel_opt}/updates/ffdecsawrapper/dvbloopback.ko
         fi
-        mkdir -p /lib/modules/`uname -r`/updates/ffdecsawrapper > /dev/null 2>&1
-        /usr/bin/install dvbloopback.ko /lib/modules/`uname -r`/updates/ffdecsawrapper
-        depmod -a
+        mkdir -p /lib/modules/${kernel_opt}/updates/ffdecsawrapper > /dev/null 2>&1
+        /usr/bin/install dvbloopback.ko /lib/modules/${kernel_opt}/updates/ffdecsawrapper
+        depmod -a ${kernel_opt}
       fi
 
 # The kernel needs to be patched if we don't
@@ -977,12 +985,12 @@ If you hit Y and your kernel needs to be patched, that will be done too.
 # to do so if it allready has been done.
 
       if [ "x$dvb_path" = "x" ]; then
-        if ! find /lib/modules/`uname -r`/updates -name dvb-core.ko -print | grep "dvb-core.ko" > /dev/null 2>&1; then
+        if ! find /lib/modules/${kernel_opt}/updates -name dvb-core.ko -print | grep "dvb-core.ko" > /dev/null 2>&1; then
           if uname -a | egrep 'Debian|Ubuntu' > /dev/null  2>&1; then
             if [ "$OS" = Debian ]; then
-              ./kernelpatch
+              ./kernelpatch ${kernel_opt}
             elif [ "$OS" = Ubuntu ] ; then
-              ./kernelpatch_ubuntu
+              ./kernelpatch_ubuntu ${kernel_opt}
             fi
           else
             echo -en "
